fabric_gen_config:

  FPGA:
    VPR:
    OpenFPGA:

  NoC:
    num_routers: 4 
    topology: mesh
    # mesh_size attribute can only be specified if the topology is mesh
    mesh_size: [2, 2]
 
    # Link is a connection between routers, can be hard or soft
    link: hard 

    # clock can be single or dual. Single clock means both FPGA and NoC use same clock, dual clock means they use different clocks
    clock: dual

  router:
    flit_width: 32
    flit_buffer_depth: 4

    router_interface:

    interface_width: 32
    interface_buffer_depth: 4









fabric_gen_config:
  FPGA:
    VPR:
    OpenFPGA:

  NoC:
    num_routers: 4 
    # topology can be mesh or custom
    # if topology is mesh, mesh_size attribute can be specified instead of connections
    # topology: mesh
    # mesh_size: [2, 2]

    topology: custom 
    # connections attribute can only be specified if the topology is custom
    # Connections should be a list. Starting with first router(index=1), each element has the indices of the routers it is connected to
    connections: [[2, 3], [1, 4], [1, 4], [2, 3]]
    # Link can only be hard for now. Link is a connection between routers, can be hard or soft
    link: soft
    # clock can be single or dual. Single clock means both FPGA and NoC use same clock, dual clock means they use different clocks
    clock: dual

  router:
    # flit_width (bits) is the width of each flit, is equal to width of data port of the router 
    flit_width: 32
    flit_buffer_depth: 4
    # router_interface can be axi_stream or credit_based
    router_interface: axi_stream
    # router_interface: credit_based
    # interface_width (bits) is the width of data port on the interface connected to injection port of router
    # interface_width can be more than flit_width. Serializer/deserializer will be used to convert flit_width data to interface_width data
    interface_width: 32
    interface_buffer_depth: 4



# ///////////// 

#     RTL: 

#     noc_freq: 

