/* Generated by Yosys 0.41+101 (git sha1 c71262f66, g++ 13.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "./benchmark/noc_bench.v:3.1-1063.10" *)
module noc(n0_idata_p0, n0_ivalid_p0, n0_ivch_p0, n0_ordy_p0, n0_odata_p0, n0_ovalid_p0, n1_idata_p0, n1_ivalid_p0, n1_ivch_p0, n1_ordy_p0, n1_odata_p0, n1_ovalid_p0, n2_idata_p0, n2_ivalid_p0, n2_ivch_p0, n2_ordy_p0, n2_odata_p0, n2_ovalid_p0, n3_idata_p0, n3_ivalid_p0, n3_ivch_p0
, n3_ordy_p0, n3_odata_p0, n3_ovalid_p0, n4_idata_p0, n4_ivalid_p0, n4_ivch_p0, n4_ordy_p0, n4_odata_p0, n4_ovalid_p0, n5_idata_p0, n5_ivalid_p0, n5_ivch_p0, n5_ordy_p0, n5_odata_p0, n5_ovalid_p0, n6_idata_p0, n6_ivalid_p0, n6_ivch_p0, n6_ordy_p0, n6_odata_p0, n6_ovalid_p0
, n7_idata_p0, n7_ivalid_p0, n7_ivch_p0, n7_ordy_p0, n7_odata_p0, n7_ovalid_p0, n8_idata_p0, n8_ivalid_p0, n8_ivch_p0, n8_ordy_p0, n8_odata_p0, n8_ovalid_p0, clk, rst_);
  (* src = "./benchmark/noc_bench.v:321.16-321.27" *)
  wire [1:0] OACK_0_x_n0;
  (* src = "./benchmark/noc_bench.v:333.16-333.27" *)
  wire [1:0] OACK_0_x_n1;
  (* src = "./benchmark/noc_bench.v:350.16-350.27" *)
  wire [1:0] OACK_0_x_n2;
  (* src = "./benchmark/noc_bench.v:347.16-347.27" *)
  wire [1:0] OACK_1_x_n2;
  (* src = "./benchmark/noc_bench.v:380.16-380.27" *)
  wire [1:0] OACK_1_x_n5;
  (* src = "./benchmark/noc_bench.v:426.16-426.27" *)
  wire [1:0] OACK_1_x_n8;
  (* src = "./benchmark/noc_bench.v:396.16-396.27" *)
  wire [1:0] OACK_2_x_n6;
  (* src = "./benchmark/noc_bench.v:408.16-408.27" *)
  wire [1:0] OACK_2_x_n7;
  (* src = "./benchmark/noc_bench.v:423.16-423.27" *)
  wire [1:0] OACK_2_x_n8;
  (* src = "./benchmark/noc_bench.v:316.16-316.27" *)
  wire [1:0] OACK_3_x_n0;
  (* src = "./benchmark/noc_bench.v:359.16-359.27" *)
  wire [1:0] OACK_3_x_n3;
  (* src = "./benchmark/noc_bench.v:393.16-393.27" *)
  wire [1:0] OACK_3_x_n6;
  (* src = "./benchmark/noc_bench.v:313.16-313.27" *)
  wire [1:0] OACK_4_x_n0;
  (* src = "./benchmark/noc_bench.v:327.16-327.27" *)
  wire [1:0] OACK_4_x_n1;
  (* src = "./benchmark/noc_bench.v:342.16-342.27" *)
  wire [1:0] OACK_4_x_n2;
  (* src = "./benchmark/noc_bench.v:356.16-356.27" *)
  wire [1:0] OACK_4_x_n3;
  (* src = "./benchmark/noc_bench.v:365.16-365.27" *)
  wire [1:0] OACK_4_x_n4;
  (* src = "./benchmark/noc_bench.v:375.16-375.27" *)
  wire [1:0] OACK_4_x_n5;
  (* src = "./benchmark/noc_bench.v:390.16-390.27" *)
  wire [1:0] OACK_4_x_n6;
  (* src = "./benchmark/noc_bench.v:404.16-404.27" *)
  wire [1:0] OACK_4_x_n7;
  (* src = "./benchmark/noc_bench.v:419.16-419.27" *)
  wire [1:0] OACK_4_x_n8;
  (* src = "./benchmark/noc_bench.v:311.32-311.44" *)
  wire [34:0] ODATA_0_x_n0;
  (* src = "./benchmark/noc_bench.v:325.32-325.44" *)
  wire [34:0] ODATA_0_x_n1;
  (* src = "./benchmark/noc_bench.v:340.32-340.44" *)
  wire [34:0] ODATA_0_x_n2;
  (* src = "./benchmark/noc_bench.v:337.32-337.44" *)
  wire [34:0] ODATA_1_x_n2;
  (* src = "./benchmark/noc_bench.v:373.32-373.44" *)
  wire [34:0] ODATA_1_x_n5;
  (* src = "./benchmark/noc_bench.v:417.32-417.44" *)
  wire [34:0] ODATA_1_x_n8;
  (* src = "./benchmark/noc_bench.v:388.32-388.44" *)
  wire [34:0] ODATA_2_x_n6;
  (* src = "./benchmark/noc_bench.v:402.32-402.44" *)
  wire [34:0] ODATA_2_x_n7;
  (* src = "./benchmark/noc_bench.v:414.32-414.44" *)
  wire [34:0] ODATA_2_x_n8;
  (* src = "./benchmark/noc_bench.v:308.32-308.44" *)
  wire [34:0] ODATA_3_x_n0;
  (* src = "./benchmark/noc_bench.v:354.32-354.44" *)
  wire [34:0] ODATA_3_x_n3;
  (* src = "./benchmark/noc_bench.v:385.32-385.44" *)
  wire [34:0] ODATA_3_x_n6;
  (* src = "./benchmark/noc_bench.v:319.16-319.27" *)
  wire [1:0] OLCK_0_x_n0;
  (* src = "./benchmark/noc_bench.v:331.16-331.27" *)
  wire [1:0] OLCK_0_x_n1;
  (* src = "./benchmark/noc_bench.v:348.16-348.27" *)
  wire [1:0] OLCK_0_x_n2;
  (* src = "./benchmark/noc_bench.v:345.16-345.27" *)
  wire [1:0] OLCK_1_x_n2;
  (* src = "./benchmark/noc_bench.v:378.16-378.27" *)
  wire [1:0] OLCK_1_x_n5;
  (* src = "./benchmark/noc_bench.v:424.16-424.27" *)
  wire [1:0] OLCK_1_x_n8;
  (* src = "./benchmark/noc_bench.v:394.16-394.27" *)
  wire [1:0] OLCK_2_x_n6;
  (* src = "./benchmark/noc_bench.v:406.16-406.27" *)
  wire [1:0] OLCK_2_x_n7;
  (* src = "./benchmark/noc_bench.v:421.16-421.27" *)
  wire [1:0] OLCK_2_x_n8;
  (* src = "./benchmark/noc_bench.v:314.16-314.27" *)
  wire [1:0] OLCK_3_x_n0;
  (* src = "./benchmark/noc_bench.v:357.16-357.27" *)
  wire [1:0] OLCK_3_x_n3;
  (* src = "./benchmark/noc_bench.v:391.16-391.27" *)
  wire [1:0] OLCK_3_x_n6;
  (* src = "./benchmark/noc_bench.v:312.16-312.27" *)
  wire [1:0] OLCK_4_x_n0;
  (* src = "./benchmark/noc_bench.v:326.16-326.27" *)
  wire [1:0] OLCK_4_x_n1;
  (* src = "./benchmark/noc_bench.v:341.16-341.27" *)
  wire [1:0] OLCK_4_x_n2;
  (* src = "./benchmark/noc_bench.v:355.16-355.27" *)
  wire [1:0] OLCK_4_x_n3;
  (* src = "./benchmark/noc_bench.v:364.16-364.27" *)
  wire [1:0] OLCK_4_x_n4;
  (* src = "./benchmark/noc_bench.v:374.16-374.27" *)
  wire [1:0] OLCK_4_x_n5;
  (* src = "./benchmark/noc_bench.v:389.16-389.27" *)
  wire [1:0] OLCK_4_x_n6;
  (* src = "./benchmark/noc_bench.v:403.16-403.27" *)
  wire [1:0] OLCK_4_x_n7;
  (* src = "./benchmark/noc_bench.v:418.16-418.27" *)
  wire [1:0] OLCK_4_x_n8;
  (* src = "./benchmark/noc_bench.v:320.16-320.27" *)
  wire [1:0] ORDY_0_x_n0;
  (* src = "./benchmark/noc_bench.v:332.16-332.27" *)
  wire [1:0] ORDY_0_x_n1;
  (* src = "./benchmark/noc_bench.v:349.16-349.27" *)
  wire [1:0] ORDY_0_x_n2;
  (* src = "./benchmark/noc_bench.v:362.16-362.27" *)
  wire [1:0] ORDY_0_x_n3;
  (* src = "./benchmark/noc_bench.v:369.16-369.27" *)
  wire [1:0] ORDY_0_x_n4;
  (* src = "./benchmark/noc_bench.v:381.16-381.27" *)
  wire [1:0] ORDY_0_x_n5;
  (* src = "./benchmark/noc_bench.v:398.16-398.27" *)
  wire [1:0] ORDY_0_x_n6;
  (* src = "./benchmark/noc_bench.v:410.16-410.27" *)
  wire [1:0] ORDY_0_x_n7;
  (* src = "./benchmark/noc_bench.v:427.16-427.27" *)
  wire [1:0] ORDY_0_x_n8;
  (* src = "./benchmark/noc_bench.v:318.16-318.27" *)
  wire [1:0] ORDY_1_x_n0;
  (* src = "./benchmark/noc_bench.v:330.16-330.27" *)
  wire [1:0] ORDY_1_x_n1;
  (* src = "./benchmark/noc_bench.v:346.16-346.27" *)
  wire [1:0] ORDY_1_x_n2;
  (* src = "./benchmark/noc_bench.v:361.16-361.27" *)
  wire [1:0] ORDY_1_x_n3;
  (* src = "./benchmark/noc_bench.v:368.16-368.27" *)
  wire [1:0] ORDY_1_x_n4;
  (* src = "./benchmark/noc_bench.v:379.16-379.27" *)
  wire [1:0] ORDY_1_x_n5;
  (* src = "./benchmark/noc_bench.v:397.16-397.27" *)
  wire [1:0] ORDY_1_x_n6;
  (* src = "./benchmark/noc_bench.v:409.16-409.27" *)
  wire [1:0] ORDY_1_x_n7;
  (* src = "./benchmark/noc_bench.v:425.16-425.27" *)
  wire [1:0] ORDY_1_x_n8;
  (* src = "./benchmark/noc_bench.v:317.16-317.27" *)
  wire [1:0] ORDY_2_x_n0;
  (* src = "./benchmark/noc_bench.v:329.16-329.27" *)
  wire [1:0] ORDY_2_x_n1;
  (* src = "./benchmark/noc_bench.v:344.16-344.27" *)
  wire [1:0] ORDY_2_x_n2;
  (* src = "./benchmark/noc_bench.v:360.16-360.27" *)
  wire [1:0] ORDY_2_x_n3;
  (* src = "./benchmark/noc_bench.v:367.16-367.27" *)
  wire [1:0] ORDY_2_x_n4;
  (* src = "./benchmark/noc_bench.v:377.16-377.27" *)
  wire [1:0] ORDY_2_x_n5;
  (* src = "./benchmark/noc_bench.v:395.16-395.27" *)
  wire [1:0] ORDY_2_x_n6;
  (* src = "./benchmark/noc_bench.v:407.16-407.27" *)
  wire [1:0] ORDY_2_x_n7;
  (* src = "./benchmark/noc_bench.v:422.16-422.27" *)
  wire [1:0] ORDY_2_x_n8;
  (* src = "./benchmark/noc_bench.v:315.16-315.27" *)
  wire [1:0] ORDY_3_x_n0;
  (* src = "./benchmark/noc_bench.v:328.16-328.27" *)
  wire [1:0] ORDY_3_x_n1;
  (* src = "./benchmark/noc_bench.v:343.16-343.27" *)
  wire [1:0] ORDY_3_x_n2;
  (* src = "./benchmark/noc_bench.v:358.16-358.27" *)
  wire [1:0] ORDY_3_x_n3;
  (* src = "./benchmark/noc_bench.v:366.16-366.27" *)
  wire [1:0] ORDY_3_x_n4;
  (* src = "./benchmark/noc_bench.v:376.16-376.27" *)
  wire [1:0] ORDY_3_x_n5;
  (* src = "./benchmark/noc_bench.v:392.16-392.27" *)
  wire [1:0] ORDY_3_x_n6;
  (* src = "./benchmark/noc_bench.v:405.16-405.27" *)
  wire [1:0] ORDY_3_x_n7;
  (* src = "./benchmark/noc_bench.v:420.16-420.27" *)
  wire [1:0] ORDY_3_x_n8;
  (* src = "./benchmark/noc_bench.v:310.18-310.31" *)
  wire OVALID_0_x_n0;
  (* src = "./benchmark/noc_bench.v:324.18-324.31" *)
  wire OVALID_0_x_n1;
  (* src = "./benchmark/noc_bench.v:339.18-339.31" *)
  wire OVALID_0_x_n2;
  (* src = "./benchmark/noc_bench.v:336.18-336.31" *)
  wire OVALID_1_x_n2;
  (* src = "./benchmark/noc_bench.v:372.18-372.31" *)
  wire OVALID_1_x_n5;
  (* src = "./benchmark/noc_bench.v:416.18-416.31" *)
  wire OVALID_1_x_n8;
  (* src = "./benchmark/noc_bench.v:387.18-387.31" *)
  wire OVALID_2_x_n6;
  (* src = "./benchmark/noc_bench.v:401.18-401.31" *)
  wire OVALID_2_x_n7;
  (* src = "./benchmark/noc_bench.v:413.18-413.31" *)
  wire OVALID_2_x_n8;
  (* src = "./benchmark/noc_bench.v:307.18-307.31" *)
  wire OVALID_3_x_n0;
  (* src = "./benchmark/noc_bench.v:353.18-353.31" *)
  wire OVALID_3_x_n3;
  (* src = "./benchmark/noc_bench.v:384.18-384.31" *)
  wire OVALID_3_x_n6;
  (* src = "./benchmark/noc_bench.v:309.15-309.26" *)
  wire OVCH_0_x_n0;
  (* src = "./benchmark/noc_bench.v:323.15-323.26" *)
  wire OVCH_0_x_n1;
  (* src = "./benchmark/noc_bench.v:338.15-338.26" *)
  wire OVCH_0_x_n2;
  (* src = "./benchmark/noc_bench.v:335.15-335.26" *)
  wire OVCH_1_x_n2;
  (* src = "./benchmark/noc_bench.v:371.15-371.26" *)
  wire OVCH_1_x_n5;
  (* src = "./benchmark/noc_bench.v:415.15-415.26" *)
  wire OVCH_1_x_n8;
  (* src = "./benchmark/noc_bench.v:386.15-386.26" *)
  wire OVCH_2_x_n6;
  (* src = "./benchmark/noc_bench.v:400.15-400.26" *)
  wire OVCH_2_x_n7;
  (* src = "./benchmark/noc_bench.v:412.15-412.26" *)
  wire OVCH_2_x_n8;
  (* src = "./benchmark/noc_bench.v:306.15-306.26" *)
  wire OVCH_3_x_n0;
  (* src = "./benchmark/noc_bench.v:352.15-352.26" *)
  wire OVCH_3_x_n3;
  (* src = "./benchmark/noc_bench.v:383.15-383.26" *)
  wire OVCH_3_x_n6;
  (* src = "./benchmark/noc_bench.v:305.15-305.26" *)
  wire OVCH_4_x_n0;
  (* src = "./benchmark/noc_bench.v:322.15-322.26" *)
  wire OVCH_4_x_n1;
  (* src = "./benchmark/noc_bench.v:334.15-334.26" *)
  wire OVCH_4_x_n2;
  (* src = "./benchmark/noc_bench.v:351.15-351.26" *)
  wire OVCH_4_x_n3;
  (* src = "./benchmark/noc_bench.v:363.15-363.26" *)
  wire OVCH_4_x_n4;
  (* src = "./benchmark/noc_bench.v:370.15-370.26" *)
  wire OVCH_4_x_n5;
  (* src = "./benchmark/noc_bench.v:382.15-382.26" *)
  wire OVCH_4_x_n6;
  (* src = "./benchmark/noc_bench.v:399.15-399.26" *)
  wire OVCH_4_x_n7;
  (* src = "./benchmark/noc_bench.v:411.15-411.26" *)
  wire OVCH_4_x_n8;
  (* src = "./benchmark/noc_bench.v:157.7-157.10" *)
  input clk;
  wire clk;
  (* src = "./benchmark/noc_bench.v:86.39-86.50" *)
  input [34:0] n0_idata_p0;
  wire [34:0] n0_idata_p0;
  (* src = "./benchmark/noc_bench.v:87.25-87.37" *)
  input n0_ivalid_p0;
  wire n0_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:88.22-88.32" *)
  input n0_ivch_p0;
  wire n0_ivch_p0;
  (* src = "./benchmark/noc_bench.v:174.23-174.32" *)
  wire [1:0] n0_oack_1;
  (* src = "./benchmark/noc_bench.v:204.23-204.32" *)
  wire [1:0] n0_oack_2;
  (* src = "./benchmark/noc_bench.v:160.39-160.49" *)
  wire [34:0] n0_odata_1;
  (* src = "./benchmark/noc_bench.v:166.39-166.49" *)
  wire [34:0] n0_odata_2;
  (* src = "./benchmark/noc_bench.v:90.39-90.50" *)
  output [34:0] n0_odata_p0;
  wire [34:0] n0_odata_p0;
  (* src = "./benchmark/noc_bench.v:175.23-175.32" *)
  wire [1:0] n0_olck_1;
  (* src = "./benchmark/noc_bench.v:205.23-205.32" *)
  wire [1:0] n0_olck_2;
  (* src = "./benchmark/noc_bench.v:89.23-89.33" *)
  output [1:0] n0_ordy_p0;
  wire [1:0] n0_ordy_p0;
  (* src = "./benchmark/noc_bench.v:161.25-161.36" *)
  wire n0_ovalid_1;
  (* src = "./benchmark/noc_bench.v:167.25-167.36" *)
  wire n0_ovalid_2;
  (* src = "./benchmark/noc_bench.v:91.25-91.37" *)
  output n0_ovalid_p0;
  wire n0_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:176.22-176.31" *)
  wire n0_ovch_1;
  (* src = "./benchmark/noc_bench.v:206.22-206.31" *)
  wire n0_ovch_2;
  (* src = "./benchmark/noc_bench.v:94.39-94.50" *)
  input [34:0] n1_idata_p0;
  wire [34:0] n1_idata_p0;
  (* src = "./benchmark/noc_bench.v:95.25-95.37" *)
  input n1_ivalid_p0;
  wire n1_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:96.22-96.32" *)
  input n1_ivch_p0;
  wire n1_ivch_p0;
  (* src = "./benchmark/noc_bench.v:192.23-192.32" *)
  wire [1:0] n1_oack_1;
  (* src = "./benchmark/noc_bench.v:222.23-222.32" *)
  wire [1:0] n1_oack_2;
  (* src = "./benchmark/noc_bench.v:162.23-162.32" *)
  wire [1:0] n1_oack_3;
  (* src = "./benchmark/noc_bench.v:178.39-178.49" *)
  wire [34:0] n1_odata_1;
  (* src = "./benchmark/noc_bench.v:184.39-184.49" *)
  wire [34:0] n1_odata_2;
  (* src = "./benchmark/noc_bench.v:172.39-172.49" *)
  wire [34:0] n1_odata_3;
  (* src = "./benchmark/noc_bench.v:98.39-98.50" *)
  output [34:0] n1_odata_p0;
  wire [34:0] n1_odata_p0;
  (* src = "./benchmark/noc_bench.v:193.23-193.32" *)
  wire [1:0] n1_olck_1;
  (* src = "./benchmark/noc_bench.v:223.23-223.32" *)
  wire [1:0] n1_olck_2;
  (* src = "./benchmark/noc_bench.v:163.23-163.32" *)
  wire [1:0] n1_olck_3;
  (* src = "./benchmark/noc_bench.v:97.23-97.33" *)
  output [1:0] n1_ordy_p0;
  wire [1:0] n1_ordy_p0;
  (* src = "./benchmark/noc_bench.v:179.25-179.36" *)
  wire n1_ovalid_1;
  (* src = "./benchmark/noc_bench.v:185.25-185.36" *)
  wire n1_ovalid_2;
  (* src = "./benchmark/noc_bench.v:173.25-173.36" *)
  wire n1_ovalid_3;
  (* src = "./benchmark/noc_bench.v:99.25-99.37" *)
  output n1_ovalid_p0;
  wire n1_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:194.22-194.31" *)
  wire n1_ovch_1;
  (* src = "./benchmark/noc_bench.v:224.22-224.31" *)
  wire n1_ovch_2;
  (* src = "./benchmark/noc_bench.v:164.22-164.31" *)
  wire n1_ovch_3;
  (* src = "./benchmark/noc_bench.v:102.39-102.50" *)
  input [34:0] n2_idata_p0;
  wire [34:0] n2_idata_p0;
  (* src = "./benchmark/noc_bench.v:103.25-103.37" *)
  input n2_ivalid_p0;
  wire n2_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:104.22-104.32" *)
  input n2_ivch_p0;
  wire n2_ivch_p0;
  (* src = "./benchmark/noc_bench.v:246.23-246.32" *)
  wire [1:0] n2_oack_2;
  (* src = "./benchmark/noc_bench.v:180.23-180.32" *)
  wire [1:0] n2_oack_3;
  (* src = "./benchmark/noc_bench.v:196.39-196.49" *)
  wire [34:0] n2_odata_2;
  (* src = "./benchmark/noc_bench.v:190.39-190.49" *)
  wire [34:0] n2_odata_3;
  (* src = "./benchmark/noc_bench.v:106.39-106.50" *)
  output [34:0] n2_odata_p0;
  wire [34:0] n2_odata_p0;
  (* src = "./benchmark/noc_bench.v:247.23-247.32" *)
  wire [1:0] n2_olck_2;
  (* src = "./benchmark/noc_bench.v:181.23-181.32" *)
  wire [1:0] n2_olck_3;
  (* src = "./benchmark/noc_bench.v:105.23-105.33" *)
  output [1:0] n2_ordy_p0;
  wire [1:0] n2_ordy_p0;
  (* src = "./benchmark/noc_bench.v:197.25-197.36" *)
  wire n2_ovalid_2;
  (* src = "./benchmark/noc_bench.v:191.25-191.36" *)
  wire n2_ovalid_3;
  (* src = "./benchmark/noc_bench.v:107.25-107.37" *)
  output n2_ovalid_p0;
  wire n2_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:248.22-248.31" *)
  wire n2_ovch_2;
  (* src = "./benchmark/noc_bench.v:182.22-182.31" *)
  wire n2_ovch_3;
  (* src = "./benchmark/noc_bench.v:110.39-110.50" *)
  input [34:0] n3_idata_p0;
  wire [34:0] n3_idata_p0;
  (* src = "./benchmark/noc_bench.v:111.25-111.37" *)
  input n3_ivalid_p0;
  wire n3_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:112.22-112.32" *)
  input n3_ivch_p0;
  wire n3_ivch_p0;
  (* src = "./benchmark/noc_bench.v:168.23-168.32" *)
  wire [1:0] n3_oack_0;
  (* src = "./benchmark/noc_bench.v:228.23-228.32" *)
  wire [1:0] n3_oack_1;
  (* src = "./benchmark/noc_bench.v:264.23-264.32" *)
  wire [1:0] n3_oack_2;
  (* src = "./benchmark/noc_bench.v:202.39-202.49" *)
  wire [34:0] n3_odata_0;
  (* src = "./benchmark/noc_bench.v:208.39-208.49" *)
  wire [34:0] n3_odata_1;
  (* src = "./benchmark/noc_bench.v:214.39-214.49" *)
  wire [34:0] n3_odata_2;
  (* src = "./benchmark/noc_bench.v:114.39-114.50" *)
  output [34:0] n3_odata_p0;
  wire [34:0] n3_odata_p0;
  (* src = "./benchmark/noc_bench.v:169.23-169.32" *)
  wire [1:0] n3_olck_0;
  (* src = "./benchmark/noc_bench.v:229.23-229.32" *)
  wire [1:0] n3_olck_1;
  (* src = "./benchmark/noc_bench.v:265.23-265.32" *)
  wire [1:0] n3_olck_2;
  (* src = "./benchmark/noc_bench.v:113.23-113.33" *)
  output [1:0] n3_ordy_p0;
  wire [1:0] n3_ordy_p0;
  (* src = "./benchmark/noc_bench.v:203.25-203.36" *)
  wire n3_ovalid_0;
  (* src = "./benchmark/noc_bench.v:209.25-209.36" *)
  wire n3_ovalid_1;
  (* src = "./benchmark/noc_bench.v:215.25-215.36" *)
  wire n3_ovalid_2;
  (* src = "./benchmark/noc_bench.v:115.25-115.37" *)
  output n3_ovalid_p0;
  wire n3_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:170.22-170.31" *)
  wire n3_ovch_0;
  (* src = "./benchmark/noc_bench.v:230.22-230.31" *)
  wire n3_ovch_1;
  (* src = "./benchmark/noc_bench.v:266.22-266.31" *)
  wire n3_ovch_2;
  (* src = "./benchmark/noc_bench.v:118.39-118.50" *)
  input [34:0] n4_idata_p0;
  wire [34:0] n4_idata_p0;
  (* src = "./benchmark/noc_bench.v:119.25-119.37" *)
  input n4_ivalid_p0;
  wire n4_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:120.22-120.32" *)
  input n4_ivch_p0;
  wire n4_ivch_p0;
  (* src = "./benchmark/noc_bench.v:186.23-186.32" *)
  wire [1:0] n4_oack_0;
  (* src = "./benchmark/noc_bench.v:252.23-252.32" *)
  wire [1:0] n4_oack_1;
  (* src = "./benchmark/noc_bench.v:276.23-276.32" *)
  wire [1:0] n4_oack_2;
  (* src = "./benchmark/noc_bench.v:210.23-210.32" *)
  wire [1:0] n4_oack_3;
  (* src = "./benchmark/noc_bench.v:220.39-220.49" *)
  wire [34:0] n4_odata_0;
  (* src = "./benchmark/noc_bench.v:232.39-232.49" *)
  wire [34:0] n4_odata_1;
  (* src = "./benchmark/noc_bench.v:238.39-238.49" *)
  wire [34:0] n4_odata_2;
  (* src = "./benchmark/noc_bench.v:226.39-226.49" *)
  wire [34:0] n4_odata_3;
  (* src = "./benchmark/noc_bench.v:122.39-122.50" *)
  output [34:0] n4_odata_p0;
  wire [34:0] n4_odata_p0;
  (* src = "./benchmark/noc_bench.v:187.23-187.32" *)
  wire [1:0] n4_olck_0;
  (* src = "./benchmark/noc_bench.v:253.23-253.32" *)
  wire [1:0] n4_olck_1;
  (* src = "./benchmark/noc_bench.v:277.23-277.32" *)
  wire [1:0] n4_olck_2;
  (* src = "./benchmark/noc_bench.v:211.23-211.32" *)
  wire [1:0] n4_olck_3;
  (* src = "./benchmark/noc_bench.v:121.23-121.33" *)
  output [1:0] n4_ordy_p0;
  wire [1:0] n4_ordy_p0;
  (* src = "./benchmark/noc_bench.v:221.25-221.36" *)
  wire n4_ovalid_0;
  (* src = "./benchmark/noc_bench.v:233.25-233.36" *)
  wire n4_ovalid_1;
  (* src = "./benchmark/noc_bench.v:239.25-239.36" *)
  wire n4_ovalid_2;
  (* src = "./benchmark/noc_bench.v:227.25-227.36" *)
  wire n4_ovalid_3;
  (* src = "./benchmark/noc_bench.v:123.25-123.37" *)
  output n4_ovalid_p0;
  wire n4_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:188.22-188.31" *)
  wire n4_ovch_0;
  (* src = "./benchmark/noc_bench.v:254.22-254.31" *)
  wire n4_ovch_1;
  (* src = "./benchmark/noc_bench.v:278.22-278.31" *)
  wire n4_ovch_2;
  (* src = "./benchmark/noc_bench.v:212.22-212.31" *)
  wire n4_ovch_3;
  (* src = "./benchmark/noc_bench.v:126.39-126.50" *)
  input [34:0] n5_idata_p0;
  wire [34:0] n5_idata_p0;
  (* src = "./benchmark/noc_bench.v:127.25-127.37" *)
  input n5_ivalid_p0;
  wire n5_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:128.22-128.32" *)
  input n5_ivch_p0;
  wire n5_ivch_p0;
  (* src = "./benchmark/noc_bench.v:198.23-198.32" *)
  wire [1:0] n5_oack_0;
  (* src = "./benchmark/noc_bench.v:294.23-294.32" *)
  wire [1:0] n5_oack_2;
  (* src = "./benchmark/noc_bench.v:234.23-234.32" *)
  wire [1:0] n5_oack_3;
  (* src = "./benchmark/noc_bench.v:244.39-244.49" *)
  wire [34:0] n5_odata_0;
  (* src = "./benchmark/noc_bench.v:256.39-256.49" *)
  wire [34:0] n5_odata_2;
  (* src = "./benchmark/noc_bench.v:250.39-250.49" *)
  wire [34:0] n5_odata_3;
  (* src = "./benchmark/noc_bench.v:130.39-130.50" *)
  output [34:0] n5_odata_p0;
  wire [34:0] n5_odata_p0;
  (* src = "./benchmark/noc_bench.v:199.23-199.32" *)
  wire [1:0] n5_olck_0;
  (* src = "./benchmark/noc_bench.v:295.23-295.32" *)
  wire [1:0] n5_olck_2;
  (* src = "./benchmark/noc_bench.v:235.23-235.32" *)
  wire [1:0] n5_olck_3;
  (* src = "./benchmark/noc_bench.v:129.23-129.33" *)
  output [1:0] n5_ordy_p0;
  wire [1:0] n5_ordy_p0;
  (* src = "./benchmark/noc_bench.v:245.25-245.36" *)
  wire n5_ovalid_0;
  (* src = "./benchmark/noc_bench.v:257.25-257.36" *)
  wire n5_ovalid_2;
  (* src = "./benchmark/noc_bench.v:251.25-251.36" *)
  wire n5_ovalid_3;
  (* src = "./benchmark/noc_bench.v:131.25-131.37" *)
  output n5_ovalid_p0;
  wire n5_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:200.22-200.31" *)
  wire n5_ovch_0;
  (* src = "./benchmark/noc_bench.v:296.22-296.31" *)
  wire n5_ovch_2;
  (* src = "./benchmark/noc_bench.v:236.22-236.31" *)
  wire n5_ovch_3;
  (* src = "./benchmark/noc_bench.v:134.39-134.50" *)
  input [34:0] n6_idata_p0;
  wire [34:0] n6_idata_p0;
  (* src = "./benchmark/noc_bench.v:135.25-135.37" *)
  input n6_ivalid_p0;
  wire n6_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:136.22-136.32" *)
  input n6_ivch_p0;
  wire n6_ivch_p0;
  (* src = "./benchmark/noc_bench.v:216.23-216.32" *)
  wire [1:0] n6_oack_0;
  (* src = "./benchmark/noc_bench.v:282.23-282.32" *)
  wire [1:0] n6_oack_1;
  (* src = "./benchmark/noc_bench.v:262.39-262.49" *)
  wire [34:0] n6_odata_0;
  (* src = "./benchmark/noc_bench.v:268.39-268.49" *)
  wire [34:0] n6_odata_1;
  (* src = "./benchmark/noc_bench.v:138.39-138.50" *)
  output [34:0] n6_odata_p0;
  wire [34:0] n6_odata_p0;
  (* src = "./benchmark/noc_bench.v:217.23-217.32" *)
  wire [1:0] n6_olck_0;
  (* src = "./benchmark/noc_bench.v:283.23-283.32" *)
  wire [1:0] n6_olck_1;
  (* src = "./benchmark/noc_bench.v:137.23-137.33" *)
  output [1:0] n6_ordy_p0;
  wire [1:0] n6_ordy_p0;
  (* src = "./benchmark/noc_bench.v:263.25-263.36" *)
  wire n6_ovalid_0;
  (* src = "./benchmark/noc_bench.v:269.25-269.36" *)
  wire n6_ovalid_1;
  (* src = "./benchmark/noc_bench.v:139.25-139.37" *)
  output n6_ovalid_p0;
  wire n6_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:218.22-218.31" *)
  wire n6_ovch_0;
  (* src = "./benchmark/noc_bench.v:284.22-284.31" *)
  wire n6_ovch_1;
  (* src = "./benchmark/noc_bench.v:142.39-142.50" *)
  input [34:0] n7_idata_p0;
  wire [34:0] n7_idata_p0;
  (* src = "./benchmark/noc_bench.v:143.25-143.37" *)
  input n7_ivalid_p0;
  wire n7_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:144.22-144.32" *)
  input n7_ivch_p0;
  wire n7_ivch_p0;
  (* src = "./benchmark/noc_bench.v:240.23-240.32" *)
  wire [1:0] n7_oack_0;
  (* src = "./benchmark/noc_bench.v:300.23-300.32" *)
  wire [1:0] n7_oack_1;
  (* src = "./benchmark/noc_bench.v:270.23-270.32" *)
  wire [1:0] n7_oack_3;
  (* src = "./benchmark/noc_bench.v:274.39-274.49" *)
  wire [34:0] n7_odata_0;
  (* src = "./benchmark/noc_bench.v:286.39-286.49" *)
  wire [34:0] n7_odata_1;
  (* src = "./benchmark/noc_bench.v:280.39-280.49" *)
  wire [34:0] n7_odata_3;
  (* src = "./benchmark/noc_bench.v:146.39-146.50" *)
  output [34:0] n7_odata_p0;
  wire [34:0] n7_odata_p0;
  (* src = "./benchmark/noc_bench.v:241.23-241.32" *)
  wire [1:0] n7_olck_0;
  (* src = "./benchmark/noc_bench.v:301.23-301.32" *)
  wire [1:0] n7_olck_1;
  (* src = "./benchmark/noc_bench.v:271.23-271.32" *)
  wire [1:0] n7_olck_3;
  (* src = "./benchmark/noc_bench.v:145.23-145.33" *)
  output [1:0] n7_ordy_p0;
  wire [1:0] n7_ordy_p0;
  (* src = "./benchmark/noc_bench.v:275.25-275.36" *)
  wire n7_ovalid_0;
  (* src = "./benchmark/noc_bench.v:287.25-287.36" *)
  wire n7_ovalid_1;
  (* src = "./benchmark/noc_bench.v:281.25-281.36" *)
  wire n7_ovalid_3;
  (* src = "./benchmark/noc_bench.v:147.25-147.37" *)
  output n7_ovalid_p0;
  wire n7_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:242.22-242.31" *)
  wire n7_ovch_0;
  (* src = "./benchmark/noc_bench.v:302.22-302.31" *)
  wire n7_ovch_1;
  (* src = "./benchmark/noc_bench.v:272.22-272.31" *)
  wire n7_ovch_3;
  (* src = "./benchmark/noc_bench.v:150.39-150.50" *)
  input [34:0] n8_idata_p0;
  wire [34:0] n8_idata_p0;
  (* src = "./benchmark/noc_bench.v:151.25-151.37" *)
  input n8_ivalid_p0;
  wire n8_ivalid_p0;
  (* src = "./benchmark/noc_bench.v:152.22-152.32" *)
  input n8_ivch_p0;
  wire n8_ivch_p0;
  (* src = "./benchmark/noc_bench.v:258.23-258.32" *)
  wire [1:0] n8_oack_0;
  (* src = "./benchmark/noc_bench.v:288.23-288.32" *)
  wire [1:0] n8_oack_3;
  (* src = "./benchmark/noc_bench.v:292.39-292.49" *)
  wire [34:0] n8_odata_0;
  (* src = "./benchmark/noc_bench.v:298.39-298.49" *)
  wire [34:0] n8_odata_3;
  (* src = "./benchmark/noc_bench.v:154.39-154.50" *)
  output [34:0] n8_odata_p0;
  wire [34:0] n8_odata_p0;
  (* src = "./benchmark/noc_bench.v:259.23-259.32" *)
  wire [1:0] n8_olck_0;
  (* src = "./benchmark/noc_bench.v:289.23-289.32" *)
  wire [1:0] n8_olck_3;
  (* src = "./benchmark/noc_bench.v:153.23-153.33" *)
  output [1:0] n8_ordy_p0;
  wire [1:0] n8_ordy_p0;
  (* src = "./benchmark/noc_bench.v:293.25-293.36" *)
  wire n8_ovalid_0;
  (* src = "./benchmark/noc_bench.v:299.25-299.36" *)
  wire n8_ovalid_3;
  (* src = "./benchmark/noc_bench.v:155.25-155.37" *)
  output n8_ovalid_p0;
  wire n8_ovalid_p0;
  (* src = "./benchmark/noc_bench.v:260.22-260.31" *)
  wire n8_ovch_0;
  (* src = "./benchmark/noc_bench.v:290.22-290.31" *)
  wire n8_ovch_3;
  (* src = "./benchmark/noc_bench.v:157.12-157.16" *)
  input rst_;
  wire rst_;
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:433.8-501.2" *)
  router n0 (
    .IACK_0(2'h0),
    .IACK_1(n1_oack_3),
    .IACK_2(n3_oack_0),
    .IACK_3(2'h0),
    .IACK_4(2'h3),
    .IDATA_0(35'h000000000),
    .IDATA_1(n1_odata_3),
    .IDATA_2(n3_odata_0),
    .IDATA_3(35'h000000000),
    .IDATA_4(n0_idata_p0),
    .ILCK_0(2'h0),
    .ILCK_1(n1_olck_3),
    .ILCK_2(n3_olck_0),
    .ILCK_3(2'h0),
    .ILCK_4(2'h0),
    .IVALID_0(1'h0),
    .IVALID_1(n1_ovalid_3),
    .IVALID_2(n3_ovalid_0),
    .IVALID_3(1'h0),
    .IVALID_4(n0_ivalid_p0),
    .IVCH_0(1'h0),
    .IVCH_1(n1_ovch_3),
    .IVCH_2(n3_ovch_0),
    .IVCH_3(1'h0),
    .IVCH_4(n0_ivch_p0),
    .MY_XPOS(2'h0),
    .MY_YPOS(2'h0),
    .OACK_0(OACK_0_x_n0),
    .OACK_1(n0_oack_1),
    .OACK_2(n0_oack_2),
    .OACK_3(OACK_3_x_n0),
    .OACK_4(OACK_4_x_n0),
    .ODATA_0(ODATA_0_x_n0),
    .ODATA_1(n0_odata_1),
    .ODATA_2(n0_odata_2),
    .ODATA_3(ODATA_3_x_n0),
    .ODATA_4(n0_odata_p0),
    .OLCK_0(OLCK_0_x_n0),
    .OLCK_1(n0_olck_1),
    .OLCK_2(n0_olck_2),
    .OLCK_3(OLCK_3_x_n0),
    .OLCK_4(OLCK_4_x_n0),
    .ORDY_0(ORDY_0_x_n0),
    .ORDY_1(ORDY_1_x_n0),
    .ORDY_2(ORDY_2_x_n0),
    .ORDY_3(ORDY_3_x_n0),
    .ORDY_4(n0_ordy_p0),
    .OVALID_0(OVALID_0_x_n0),
    .OVALID_1(n0_ovalid_1),
    .OVALID_2(n0_ovalid_2),
    .OVALID_3(OVALID_3_x_n0),
    .OVALID_4(n0_ovalid_p0),
    .OVCH_0(OVCH_0_x_n0),
    .OVCH_1(n0_ovch_1),
    .OVCH_2(n0_ovch_2),
    .OVCH_3(OVCH_3_x_n0),
    .OVCH_4(OVCH_4_x_n0),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:503.9-571.2" *)
  router n1 (
    .IACK_0(2'h0),
    .IACK_1(n2_oack_3),
    .IACK_2(n4_oack_0),
    .IACK_3(n0_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(35'h000000000),
    .IDATA_1(n2_odata_3),
    .IDATA_2(n4_odata_0),
    .IDATA_3(n0_odata_1),
    .IDATA_4(n1_idata_p0),
    .ILCK_0(2'h0),
    .ILCK_1(n2_olck_3),
    .ILCK_2(n4_olck_0),
    .ILCK_3(n0_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(1'h0),
    .IVALID_1(n2_ovalid_3),
    .IVALID_2(n4_ovalid_0),
    .IVALID_3(n0_ovalid_1),
    .IVALID_4(n1_ivalid_p0),
    .IVCH_0(1'h0),
    .IVCH_1(n2_ovch_3),
    .IVCH_2(n4_ovch_0),
    .IVCH_3(n0_ovch_1),
    .IVCH_4(n1_ivch_p0),
    .MY_XPOS(2'h1),
    .MY_YPOS(2'h0),
    .OACK_0(OACK_0_x_n1),
    .OACK_1(n1_oack_1),
    .OACK_2(n1_oack_2),
    .OACK_3(n1_oack_3),
    .OACK_4(OACK_4_x_n1),
    .ODATA_0(ODATA_0_x_n1),
    .ODATA_1(n1_odata_1),
    .ODATA_2(n1_odata_2),
    .ODATA_3(n1_odata_3),
    .ODATA_4(n1_odata_p0),
    .OLCK_0(OLCK_0_x_n1),
    .OLCK_1(n1_olck_1),
    .OLCK_2(n1_olck_2),
    .OLCK_3(n1_olck_3),
    .OLCK_4(OLCK_4_x_n1),
    .ORDY_0(ORDY_0_x_n1),
    .ORDY_1(ORDY_1_x_n1),
    .ORDY_2(ORDY_2_x_n1),
    .ORDY_3(ORDY_3_x_n1),
    .ORDY_4(n1_ordy_p0),
    .OVALID_0(OVALID_0_x_n1),
    .OVALID_1(n1_ovalid_1),
    .OVALID_2(n1_ovalid_2),
    .OVALID_3(n1_ovalid_3),
    .OVALID_4(n1_ovalid_p0),
    .OVCH_0(OVCH_0_x_n1),
    .OVCH_1(n1_ovch_1),
    .OVCH_2(n1_ovch_2),
    .OVCH_3(n1_ovch_3),
    .OVCH_4(OVCH_4_x_n1),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:573.9-641.2" *)
  router n2 (
    .IACK_0(2'h0),
    .IACK_1(2'h0),
    .IACK_2(n5_oack_0),
    .IACK_3(n1_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(35'h000000000),
    .IDATA_1(35'h000000000),
    .IDATA_2(n5_odata_0),
    .IDATA_3(n1_odata_1),
    .IDATA_4(n2_idata_p0),
    .ILCK_0(2'h0),
    .ILCK_1(2'h0),
    .ILCK_2(n5_olck_0),
    .ILCK_3(n1_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(1'h0),
    .IVALID_1(1'h0),
    .IVALID_2(n5_ovalid_0),
    .IVALID_3(n1_ovalid_1),
    .IVALID_4(n2_ivalid_p0),
    .IVCH_0(1'h0),
    .IVCH_1(1'h0),
    .IVCH_2(n5_ovch_0),
    .IVCH_3(n1_ovch_1),
    .IVCH_4(n2_ivch_p0),
    .MY_XPOS(2'h2),
    .MY_YPOS(2'h0),
    .OACK_0(OACK_0_x_n2),
    .OACK_1(OACK_1_x_n2),
    .OACK_2(n2_oack_2),
    .OACK_3(n2_oack_3),
    .OACK_4(OACK_4_x_n2),
    .ODATA_0(ODATA_0_x_n2),
    .ODATA_1(ODATA_1_x_n2),
    .ODATA_2(n2_odata_2),
    .ODATA_3(n2_odata_3),
    .ODATA_4(n2_odata_p0),
    .OLCK_0(OLCK_0_x_n2),
    .OLCK_1(OLCK_1_x_n2),
    .OLCK_2(n2_olck_2),
    .OLCK_3(n2_olck_3),
    .OLCK_4(OLCK_4_x_n2),
    .ORDY_0(ORDY_0_x_n2),
    .ORDY_1(ORDY_1_x_n2),
    .ORDY_2(ORDY_2_x_n2),
    .ORDY_3(ORDY_3_x_n2),
    .ORDY_4(n2_ordy_p0),
    .OVALID_0(OVALID_0_x_n2),
    .OVALID_1(OVALID_1_x_n2),
    .OVALID_2(n2_ovalid_2),
    .OVALID_3(n2_ovalid_3),
    .OVALID_4(n2_ovalid_p0),
    .OVCH_0(OVCH_0_x_n2),
    .OVCH_1(OVCH_1_x_n2),
    .OVCH_2(n2_ovch_2),
    .OVCH_3(n2_ovch_3),
    .OVCH_4(OVCH_4_x_n2),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:643.8-711.2" *)
  router n3 (
    .IACK_0(n0_oack_2),
    .IACK_1(n4_oack_3),
    .IACK_2(n6_oack_0),
    .IACK_3(2'h0),
    .IACK_4(2'h3),
    .IDATA_0(n0_odata_2),
    .IDATA_1(n4_odata_3),
    .IDATA_2(n6_odata_0),
    .IDATA_3(35'h000000000),
    .IDATA_4(n3_idata_p0),
    .ILCK_0(n0_olck_2),
    .ILCK_1(n4_olck_3),
    .ILCK_2(n6_olck_0),
    .ILCK_3(2'h0),
    .ILCK_4(2'h0),
    .IVALID_0(n0_ovalid_2),
    .IVALID_1(n4_ovalid_3),
    .IVALID_2(n6_ovalid_0),
    .IVALID_3(1'h0),
    .IVALID_4(n3_ivalid_p0),
    .IVCH_0(n0_ovch_2),
    .IVCH_1(n4_ovch_3),
    .IVCH_2(n6_ovch_0),
    .IVCH_3(1'h0),
    .IVCH_4(n3_ivch_p0),
    .MY_XPOS(2'h0),
    .MY_YPOS(2'h1),
    .OACK_0(n3_oack_0),
    .OACK_1(n3_oack_1),
    .OACK_2(n3_oack_2),
    .OACK_3(OACK_3_x_n3),
    .OACK_4(OACK_4_x_n3),
    .ODATA_0(n3_odata_0),
    .ODATA_1(n3_odata_1),
    .ODATA_2(n3_odata_2),
    .ODATA_3(ODATA_3_x_n3),
    .ODATA_4(n3_odata_p0),
    .OLCK_0(n3_olck_0),
    .OLCK_1(n3_olck_1),
    .OLCK_2(n3_olck_2),
    .OLCK_3(OLCK_3_x_n3),
    .OLCK_4(OLCK_4_x_n3),
    .ORDY_0(ORDY_0_x_n3),
    .ORDY_1(ORDY_1_x_n3),
    .ORDY_2(ORDY_2_x_n3),
    .ORDY_3(ORDY_3_x_n3),
    .ORDY_4(n3_ordy_p0),
    .OVALID_0(n3_ovalid_0),
    .OVALID_1(n3_ovalid_1),
    .OVALID_2(n3_ovalid_2),
    .OVALID_3(OVALID_3_x_n3),
    .OVALID_4(n3_ovalid_p0),
    .OVCH_0(n3_ovch_0),
    .OVCH_1(n3_ovch_1),
    .OVCH_2(n3_ovch_2),
    .OVCH_3(OVCH_3_x_n3),
    .OVCH_4(OVCH_4_x_n3),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:713.8-781.2" *)
  router n4 (
    .IACK_0(n1_oack_2),
    .IACK_1(n5_oack_3),
    .IACK_2(n7_oack_0),
    .IACK_3(n3_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(n1_odata_2),
    .IDATA_1(n5_odata_3),
    .IDATA_2(n7_odata_0),
    .IDATA_3(n3_odata_1),
    .IDATA_4(n4_idata_p0),
    .ILCK_0(n1_olck_2),
    .ILCK_1(n5_olck_3),
    .ILCK_2(n7_olck_0),
    .ILCK_3(n3_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(n1_ovalid_2),
    .IVALID_1(n5_ovalid_3),
    .IVALID_2(n7_ovalid_0),
    .IVALID_3(n3_ovalid_1),
    .IVALID_4(n4_ivalid_p0),
    .IVCH_0(n1_ovch_2),
    .IVCH_1(n5_ovch_3),
    .IVCH_2(n7_ovch_0),
    .IVCH_3(n3_ovch_1),
    .IVCH_4(n4_ivch_p0),
    .MY_XPOS(2'h1),
    .MY_YPOS(2'h1),
    .OACK_0(n4_oack_0),
    .OACK_1(n4_oack_1),
    .OACK_2(n4_oack_2),
    .OACK_3(n4_oack_3),
    .OACK_4(OACK_4_x_n4),
    .ODATA_0(n4_odata_0),
    .ODATA_1(n4_odata_1),
    .ODATA_2(n4_odata_2),
    .ODATA_3(n4_odata_3),
    .ODATA_4(n4_odata_p0),
    .OLCK_0(n4_olck_0),
    .OLCK_1(n4_olck_1),
    .OLCK_2(n4_olck_2),
    .OLCK_3(n4_olck_3),
    .OLCK_4(OLCK_4_x_n4),
    .ORDY_0(ORDY_0_x_n4),
    .ORDY_1(ORDY_1_x_n4),
    .ORDY_2(ORDY_2_x_n4),
    .ORDY_3(ORDY_3_x_n4),
    .ORDY_4(n4_ordy_p0),
    .OVALID_0(n4_ovalid_0),
    .OVALID_1(n4_ovalid_1),
    .OVALID_2(n4_ovalid_2),
    .OVALID_3(n4_ovalid_3),
    .OVALID_4(n4_ovalid_p0),
    .OVCH_0(n4_ovch_0),
    .OVCH_1(n4_ovch_1),
    .OVCH_2(n4_ovch_2),
    .OVCH_3(n4_ovch_3),
    .OVCH_4(OVCH_4_x_n4),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:783.9-851.2" *)
  router n5 (
    .IACK_0(n2_oack_2),
    .IACK_1(2'h0),
    .IACK_2(n8_oack_0),
    .IACK_3(n4_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(n2_odata_2),
    .IDATA_1(35'h000000000),
    .IDATA_2(n8_odata_0),
    .IDATA_3(n4_odata_1),
    .IDATA_4(n5_idata_p0),
    .ILCK_0(n2_olck_2),
    .ILCK_1(2'h0),
    .ILCK_2(n8_olck_0),
    .ILCK_3(n4_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(n2_ovalid_2),
    .IVALID_1(1'h0),
    .IVALID_2(n8_ovalid_0),
    .IVALID_3(n4_ovalid_1),
    .IVALID_4(n5_ivalid_p0),
    .IVCH_0(n2_ovch_2),
    .IVCH_1(1'h0),
    .IVCH_2(n8_ovch_0),
    .IVCH_3(n4_ovch_1),
    .IVCH_4(n5_ivch_p0),
    .MY_XPOS(2'h2),
    .MY_YPOS(2'h1),
    .OACK_0(n5_oack_0),
    .OACK_1(OACK_1_x_n5),
    .OACK_2(n5_oack_2),
    .OACK_3(n5_oack_3),
    .OACK_4(OACK_4_x_n5),
    .ODATA_0(n5_odata_0),
    .ODATA_1(ODATA_1_x_n5),
    .ODATA_2(n5_odata_2),
    .ODATA_3(n5_odata_3),
    .ODATA_4(n5_odata_p0),
    .OLCK_0(n5_olck_0),
    .OLCK_1(OLCK_1_x_n5),
    .OLCK_2(n5_olck_2),
    .OLCK_3(n5_olck_3),
    .OLCK_4(OLCK_4_x_n5),
    .ORDY_0(ORDY_0_x_n5),
    .ORDY_1(ORDY_1_x_n5),
    .ORDY_2(ORDY_2_x_n5),
    .ORDY_3(ORDY_3_x_n5),
    .ORDY_4(n5_ordy_p0),
    .OVALID_0(n5_ovalid_0),
    .OVALID_1(OVALID_1_x_n5),
    .OVALID_2(n5_ovalid_2),
    .OVALID_3(n5_ovalid_3),
    .OVALID_4(n5_ovalid_p0),
    .OVCH_0(n5_ovch_0),
    .OVCH_1(OVCH_1_x_n5),
    .OVCH_2(n5_ovch_2),
    .OVCH_3(n5_ovch_3),
    .OVCH_4(OVCH_4_x_n5),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:853.9-921.2" *)
  router n6 (
    .IACK_0(n3_oack_2),
    .IACK_1(n7_oack_3),
    .IACK_2(2'h0),
    .IACK_3(2'h0),
    .IACK_4(2'h3),
    .IDATA_0(n3_odata_2),
    .IDATA_1(n7_odata_3),
    .IDATA_2(35'h000000000),
    .IDATA_3(35'h000000000),
    .IDATA_4(n6_idata_p0),
    .ILCK_0(n3_olck_2),
    .ILCK_1(n7_olck_3),
    .ILCK_2(2'h0),
    .ILCK_3(2'h0),
    .ILCK_4(2'h0),
    .IVALID_0(n3_ovalid_2),
    .IVALID_1(n7_ovalid_3),
    .IVALID_2(1'h0),
    .IVALID_3(1'h0),
    .IVALID_4(n6_ivalid_p0),
    .IVCH_0(n3_ovch_2),
    .IVCH_1(n7_ovch_3),
    .IVCH_2(1'h0),
    .IVCH_3(1'h0),
    .IVCH_4(n6_ivch_p0),
    .MY_XPOS(2'h0),
    .MY_YPOS(2'h2),
    .OACK_0(n6_oack_0),
    .OACK_1(n6_oack_1),
    .OACK_2(OACK_2_x_n6),
    .OACK_3(OACK_3_x_n6),
    .OACK_4(OACK_4_x_n6),
    .ODATA_0(n6_odata_0),
    .ODATA_1(n6_odata_1),
    .ODATA_2(ODATA_2_x_n6),
    .ODATA_3(ODATA_3_x_n6),
    .ODATA_4(n6_odata_p0),
    .OLCK_0(n6_olck_0),
    .OLCK_1(n6_olck_1),
    .OLCK_2(OLCK_2_x_n6),
    .OLCK_3(OLCK_3_x_n6),
    .OLCK_4(OLCK_4_x_n6),
    .ORDY_0(ORDY_0_x_n6),
    .ORDY_1(ORDY_1_x_n6),
    .ORDY_2(ORDY_2_x_n6),
    .ORDY_3(ORDY_3_x_n6),
    .ORDY_4(n6_ordy_p0),
    .OVALID_0(n6_ovalid_0),
    .OVALID_1(n6_ovalid_1),
    .OVALID_2(OVALID_2_x_n6),
    .OVALID_3(OVALID_3_x_n6),
    .OVALID_4(n6_ovalid_p0),
    .OVCH_0(n6_ovch_0),
    .OVCH_1(n6_ovch_1),
    .OVCH_2(OVCH_2_x_n6),
    .OVCH_3(OVCH_3_x_n6),
    .OVCH_4(OVCH_4_x_n6),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:923.9-991.2" *)
  router n7 (
    .IACK_0(n4_oack_2),
    .IACK_1(n8_oack_3),
    .IACK_2(2'h0),
    .IACK_3(n6_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(n4_odata_2),
    .IDATA_1(n8_odata_3),
    .IDATA_2(35'h000000000),
    .IDATA_3(n6_odata_1),
    .IDATA_4(n7_idata_p0),
    .ILCK_0(n4_olck_2),
    .ILCK_1(n8_olck_3),
    .ILCK_2(2'h0),
    .ILCK_3(n6_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(n4_ovalid_2),
    .IVALID_1(n8_ovalid_3),
    .IVALID_2(1'h0),
    .IVALID_3(n6_ovalid_1),
    .IVALID_4(n7_ivalid_p0),
    .IVCH_0(n4_ovch_2),
    .IVCH_1(n8_ovch_3),
    .IVCH_2(1'h0),
    .IVCH_3(n6_ovch_1),
    .IVCH_4(n7_ivch_p0),
    .MY_XPOS(2'h1),
    .MY_YPOS(2'h2),
    .OACK_0(n7_oack_0),
    .OACK_1(n7_oack_1),
    .OACK_2(OACK_2_x_n7),
    .OACK_3(n7_oack_3),
    .OACK_4(OACK_4_x_n7),
    .ODATA_0(n7_odata_0),
    .ODATA_1(n7_odata_1),
    .ODATA_2(ODATA_2_x_n7),
    .ODATA_3(n7_odata_3),
    .ODATA_4(n7_odata_p0),
    .OLCK_0(n7_olck_0),
    .OLCK_1(n7_olck_1),
    .OLCK_2(OLCK_2_x_n7),
    .OLCK_3(n7_olck_3),
    .OLCK_4(OLCK_4_x_n7),
    .ORDY_0(ORDY_0_x_n7),
    .ORDY_1(ORDY_1_x_n7),
    .ORDY_2(ORDY_2_x_n7),
    .ORDY_3(ORDY_3_x_n7),
    .ORDY_4(n7_ordy_p0),
    .OVALID_0(n7_ovalid_0),
    .OVALID_1(n7_ovalid_1),
    .OVALID_2(OVALID_2_x_n7),
    .OVALID_3(n7_ovalid_3),
    .OVALID_4(n7_ovalid_p0),
    .OVCH_0(n7_ovch_0),
    .OVCH_1(n7_ovch_1),
    .OVCH_2(OVCH_2_x_n7),
    .OVCH_3(n7_ovch_3),
    .OVCH_4(OVCH_4_x_n7),
    .RST_(rst_),
    .clk(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./benchmark/noc_bench.v:993.9-1061.2" *)
  router n8 (
    .IACK_0(n5_oack_2),
    .IACK_1(2'h0),
    .IACK_2(2'h0),
    .IACK_3(n7_oack_1),
    .IACK_4(2'h3),
    .IDATA_0(n5_odata_2),
    .IDATA_1(35'h000000000),
    .IDATA_2(35'h000000000),
    .IDATA_3(n7_odata_1),
    .IDATA_4(n8_idata_p0),
    .ILCK_0(n5_olck_2),
    .ILCK_1(2'h0),
    .ILCK_2(2'h0),
    .ILCK_3(n7_olck_1),
    .ILCK_4(2'h0),
    .IVALID_0(n5_ovalid_2),
    .IVALID_1(1'h0),
    .IVALID_2(1'h0),
    .IVALID_3(n7_ovalid_1),
    .IVALID_4(n8_ivalid_p0),
    .IVCH_0(n5_ovch_2),
    .IVCH_1(1'h0),
    .IVCH_2(1'h0),
    .IVCH_3(n7_ovch_1),
    .IVCH_4(n8_ivch_p0),
    .MY_XPOS(2'h2),
    .MY_YPOS(2'h2),
    .OACK_0(n8_oack_0),
    .OACK_1(OACK_1_x_n8),
    .OACK_2(OACK_2_x_n8),
    .OACK_3(n8_oack_3),
    .OACK_4(OACK_4_x_n8),
    .ODATA_0(n8_odata_0),
    .ODATA_1(ODATA_1_x_n8),
    .ODATA_2(ODATA_2_x_n8),
    .ODATA_3(n8_odata_3),
    .ODATA_4(n8_odata_p0),
    .OLCK_0(n8_olck_0),
    .OLCK_1(OLCK_1_x_n8),
    .OLCK_2(OLCK_2_x_n8),
    .OLCK_3(n8_olck_3),
    .OLCK_4(OLCK_4_x_n8),
    .ORDY_0(ORDY_0_x_n8),
    .ORDY_1(ORDY_1_x_n8),
    .ORDY_2(ORDY_2_x_n8),
    .ORDY_3(ORDY_3_x_n8),
    .ORDY_4(n8_ordy_p0),
    .OVALID_0(n8_ovalid_0),
    .OVALID_1(OVALID_1_x_n8),
    .OVALID_2(OVALID_2_x_n8),
    .OVALID_3(n8_ovalid_3),
    .OVALID_4(n8_ovalid_p0),
    .OVCH_0(n8_ovch_0),
    .OVCH_1(OVCH_1_x_n8),
    .OVCH_2(OVCH_2_x_n8),
    .OVCH_3(n8_ovch_3),
    .OVCH_4(OVCH_4_x_n8),
    .RST_(rst_),
    .clk(clk)
  );
endmodule
