onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /noc_test/REF_DUT/n0/idata_0
add wave -noupdate /noc_test/REF_DUT/n0/ivalid_0
add wave -noupdate /noc_test/REF_DUT/n0/ivch_0
add wave -noupdate /noc_test/REF_DUT/n0/oack_0
add wave -noupdate /noc_test/REF_DUT/n0/ordy_0
add wave -noupdate /noc_test/REF_DUT/n0/olck_0
add wave -noupdate /noc_test/REF_DUT/n0/idata_1
add wave -noupdate /noc_test/REF_DUT/n0/ivalid_1
add wave -noupdate /noc_test/REF_DUT/n0/ivch_1
add wave -noupdate /noc_test/REF_DUT/n0/oack_1
add wave -noupdate /noc_test/REF_DUT/n0/ordy_1
add wave -noupdate /noc_test/REF_DUT/n0/olck_1
add wave -noupdate /noc_test/REF_DUT/n0/idata_2
add wave -noupdate /noc_test/REF_DUT/n0/ivalid_2
add wave -noupdate /noc_test/REF_DUT/n0/ivch_2
add wave -noupdate /noc_test/REF_DUT/n0/oack_2
add wave -noupdate /noc_test/REF_DUT/n0/ordy_2
add wave -noupdate /noc_test/REF_DUT/n0/olck_2
add wave -noupdate /noc_test/REF_DUT/n0/idata_3
add wave -noupdate /noc_test/REF_DUT/n0/ivalid_3
add wave -noupdate /noc_test/REF_DUT/n0/ivch_3
add wave -noupdate /noc_test/REF_DUT/n0/oack_3
add wave -noupdate /noc_test/REF_DUT/n0/ordy_3
add wave -noupdate /noc_test/REF_DUT/n0/olck_3
add wave -noupdate /noc_test/REF_DUT/n0/idata_4
add wave -noupdate /noc_test/REF_DUT/n0/ivalid_4
add wave -noupdate /noc_test/REF_DUT/n0/ivch_4
add wave -noupdate /noc_test/REF_DUT/n0/oack_4
add wave -noupdate /noc_test/REF_DUT/n0/ordy_4
add wave -noupdate /noc_test/REF_DUT/n0/olck_4
add wave -noupdate /noc_test/REF_DUT/n0/odata_0
add wave -noupdate /noc_test/REF_DUT/n0/ovalid_0
add wave -noupdate /noc_test/REF_DUT/n0/ovch_0
add wave -noupdate /noc_test/REF_DUT/n0/iack_0
add wave -noupdate /noc_test/REF_DUT/n0/ilck_0
add wave -noupdate /noc_test/REF_DUT/n0/odata_1
add wave -noupdate /noc_test/REF_DUT/n0/ovalid_1
add wave -noupdate /noc_test/REF_DUT/n0/ovch_1
add wave -noupdate /noc_test/REF_DUT/n0/iack_1
add wave -noupdate /noc_test/REF_DUT/n0/ilck_1
add wave -noupdate /noc_test/REF_DUT/n0/odata_2
add wave -noupdate /noc_test/REF_DUT/n0/ovalid_2
add wave -noupdate /noc_test/REF_DUT/n0/ovch_2
add wave -noupdate /noc_test/REF_DUT/n0/iack_2
add wave -noupdate /noc_test/REF_DUT/n0/ilck_2
add wave -noupdate /noc_test/REF_DUT/n0/odata_3
add wave -noupdate /noc_test/REF_DUT/n0/ovalid_3
add wave -noupdate /noc_test/REF_DUT/n0/ovch_3
add wave -noupdate /noc_test/REF_DUT/n0/iack_3
add wave -noupdate /noc_test/REF_DUT/n0/ilck_3
add wave -noupdate /noc_test/REF_DUT/n0/odata_4
add wave -noupdate /noc_test/REF_DUT/n0/ovalid_4
add wave -noupdate /noc_test/REF_DUT/n0/ovch_4
add wave -noupdate /noc_test/REF_DUT/n0/iack_4
add wave -noupdate /noc_test/REF_DUT/n0/ilck_4
add wave -noupdate /noc_test/REF_DUT/n0/my_xpos
add wave -noupdate /noc_test/REF_DUT/n0/my_ypos
add wave -noupdate /noc_test/REF_DUT/n0/clk
add wave -noupdate /noc_test/REF_DUT/n0/rst_
add wave -noupdate /noc_test/REF_DUT/n0/ic_odata_0
add wave -noupdate /noc_test/REF_DUT/n0/ic_odata_1
add wave -noupdate /noc_test/REF_DUT/n0/ic_odata_2
add wave -noupdate /noc_test/REF_DUT/n0/ic_odata_3
add wave -noupdate /noc_test/REF_DUT/n0/ic_odata_4
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovalid_0
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovalid_1
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovalid_2
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovalid_3
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovalid_4
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovch_0
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovch_1
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovch_2
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovch_3
add wave -noupdate /noc_test/REF_DUT/n0/ic_ovch_4
add wave -noupdate /noc_test/REF_DUT/n0/ic_port_0
add wave -noupdate /noc_test/REF_DUT/n0/ic_port_1
add wave -noupdate /noc_test/REF_DUT/n0/ic_port_2
add wave -noupdate /noc_test/REF_DUT/n0/ic_port_3
add wave -noupdate /noc_test/REF_DUT/n0/ic_port_4
add wave -noupdate /noc_test/REF_DUT/n0/ic_req_0
add wave -noupdate /noc_test/REF_DUT/n0/ic_req_1
add wave -noupdate /noc_test/REF_DUT/n0/ic_req_2
add wave -noupdate /noc_test/REF_DUT/n0/ic_req_3
add wave -noupdate /noc_test/REF_DUT/n0/ic_req_4
add wave -noupdate /noc_test/REF_DUT/n0/cb_odata_0
add wave -noupdate /noc_test/REF_DUT/n0/cb_odata_1
add wave -noupdate /noc_test/REF_DUT/n0/cb_odata_2
add wave -noupdate /noc_test/REF_DUT/n0/cb_odata_3
add wave -noupdate /noc_test/REF_DUT/n0/cb_odata_4
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovalid_0
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovalid_1
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovalid_2
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovalid_3
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovalid_4
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovch_0
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovch_1
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovch_2
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovch_3
add wave -noupdate /noc_test/REF_DUT/n0/cb_ovch_4
add wave -noupdate /noc_test/REF_DUT/n0/cb_grt_0
add wave -noupdate /noc_test/REF_DUT/n0/cb_grt_1
add wave -noupdate /noc_test/REF_DUT/n0/cb_grt_2
add wave -noupdate /noc_test/REF_DUT/n0/cb_grt_3
add wave -noupdate /noc_test/REF_DUT/n0/cb_grt_4
add wave -noupdate /noc_test/REF_DUT/n0/oc_ordy_0
add wave -noupdate /noc_test/REF_DUT/n0/oc_ordy_1
add wave -noupdate /noc_test/REF_DUT/n0/oc_ordy_2
add wave -noupdate /noc_test/REF_DUT/n0/oc_ordy_3
add wave -noupdate /noc_test/REF_DUT/n0/oc_ordy_4
add wave -noupdate /noc_test/REF_DUT/n0/oc_olck_0
add wave -noupdate /noc_test/REF_DUT/n0/oc_olck_1
add wave -noupdate /noc_test/REF_DUT/n0/oc_olck_2
add wave -noupdate /noc_test/REF_DUT/n0/oc_olck_3
add wave -noupdate /noc_test/REF_DUT/n0/oc_olck_4
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {120990 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 294
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {991890 ps}
